### ISSUE TITLE
[Bug]: Failed server authentication with specified user credentials

### ISSUE THREAD

**Issue by 3l0w** [ismet55555/yojenkins#136] opened 2022-06-21 15:23 UTC
### What happened?

Any request fails, except the one who created the api token

### How can we reproduce this?

Setup a jenkins
Try go connect using a token or the automated way
use any command

### Command `--debug` output

```bash
yojenkins server info --debug
```

```
[ LOGGING LEVEL ] : DEBUG

[  TIME  ] [ MS ] [FILENAME              :  LN] MESSAGE
---------------------------------------------------------------------------
[17:21:40] [364 ] [cli_utility.py          :  64] Tool version: 0.0.72
[17:21:40] [364 ] [cli_utility.py          :  76] System information:
[17:21:40] [364 ] [cli_utility.py          :  77]     - System:    Linux
[17:21:40] [365 ] [cli_utility.py          :  78]     - Release:   5.16.15-arch1-1
[17:21:40] [365 ] [cli_utility.py          :  79]     - Version:   #1 SMP PREEMPT Thu, 17 Mar 2022 00:30:09 +0000
[17:21:40] [365 ] [cli_utility.py          :  80]     - Machine:   x86_64
[17:21:40] [368 ] [cli_utility.py          :  81]     - Processor: 
[17:21:40] [369 ] [cli_utility.py          :  82]     - Python:    3.9.9 
[17:21:40] [369 ] [cli_utility.py          :  83]     - In Docker: False
[17:21:40] [370 ] [cli_utility.py          :  84]     - Bundled:   False
[17:21:40] [370 ] [utility.py              : 131] Loading specified local .json file: '/home/fl0w/.yojenkins/history' ...
[17:21:40] [370 ] [utility.py              : 142] Successfully loaded local .json file
[17:21:40] [371 ] [cli_utility.py          : 245] Logging command to command history file: "/home/fl0w/.yojenkins/history" ...
[17:21:40] [372 ] [rest.py                 :  32] Starting new requests session (Type: FuturesSession) ...
[17:21:40] [372 ] [auth.py                 : 381] Successfully found credential file "credentials" found in user configuration directory: /home/fl0w/.yojenkins
[17:21:40] [372 ] [utility.py              : 131] Loading specified local .toml file: '/home/fl0w/.yojenkins/credentials' ...
[17:21:40] [373 ] [utility.py              : 142] Successfully loaded local .toml file
[17:21:40] [373 ] [auth.py                 : 435] Number of listed profiles found: 1
[17:21:40] [373 ] [auth.py                 : 441] Ignoring profiles that do not have at least the following keys: jenkins_server_url, username ...
[17:21:40] [374 ] [auth.py                 : 455]     - Profile 1 of 1: "default" - OK
[17:21:40] [374 ] [auth.py                 : 484] Argument "--profile" was not specified
[17:21:40] [374 ] [auth.py                 : 500] Environmental Variable "YOJENKINS_PROFILE" not set
[17:21:40] [374 ] [auth.py                 : 508] Successfully found "default" profile in the configuration file
[17:21:40] [375 ] [auth.py                 : 530] The following profile has been loaded:
[17:21:40] [375 ] [auth.py                 : 531]     - Profile:             default
[17:21:40] [375 ] [auth.py                 : 532]     - Jenkins Server URL:  https://jenkins.****.fr
[17:21:40] [375 ] [auth.py                 : 533]     - Username:            fl0w
[17:21:40] [376 ] [auth.py                 : 587]     - API Token:           **********************************
[17:21:40] [377 ] [rest.py                 :  98] Checking if server is reachable: "https://jenkins.****.fr/login" ...
[17:21:40] [378 ] [rest.py                 : 157] Request URL: https://jenkins.****.fr/login
[17:21:40] [688 ] [rest.py                 : 241] Request summary:*
*[17:21:40] [689 ] [rest.py                 : 242]    - Request:          HEAD - https://jenkins.****.fr/login
[17:21:40] [690 ] [rest.py                 : 243]    - Redirects:        Allow 
[17:21:40] [691 ] [rest.py                 : 244]    - Elapsed time:     0.312 seconds
[17:21:40] [691 ] [rest.py                 : 245]    - Response headers: text/plain; charset=utf-8 (Content Length Bytes: N/A)
[17:21:40] [692 ] [rest.py                 : 246]    - Status code:      400 (Bad Request)
[17:21:40] [692 ] [rest.py                 : 107] Successfully found server is reachable
[17:21:40] [693 ] [auth.py                 : 621] Checking authentication to Jenkins server: https://jenkins.****.fr ...
[17:21:40] [693 ] [auth.py                 : 673] Verifying server authentication by requesting user information ...
[17:21:40] [694 ] [rest.py                 : 157] Request URL: https://jenkins.****.fr/me/api/json
[17:21:40] [946 ] [rest.py                 : 241] Request summary:
[17:21:40] [947 ] [rest.py                 : 242]    - Request:          HEAD - https://jenkins.****.fr/me/api/json
[17:21:40] [948 ] [rest.py                 : 243]    - Redirects:        Allow 
[17:21:40] [948 ] [rest.py                 : 244]    - Elapsed time:     0.254 seconds
[17:21:40] [949 ] [rest.py                 : 245]    - Response headers: text/plain; charset=utf-8 (Content Length Bytes: N/A)
[17:21:40] [949 ] [rest.py                 : 246]    - Status code:      400 (Bad Request)
Failed server authentication with specified user credentials
```

### Version of `yojenkins`

0.0.72

### Where was `yojenkins` run in relation to the Jenkins server?

Remotely

### Was the Jenkins server containerized?

No

### Which operating systems were you using when this happened?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] Other
- [ ] I don't know

### How is your day going?

Pretty good

**Comment by kwmlodozeniec** [comment] 2022-06-21 16:49
This could be due to a bad URL. Could you post your credentials file with sensitive information redacted?

**Comment by 3l0w** [comment] 2022-06-21 16:51
Yup sure there is is:
```toml
# -*- mode: toml -*-
# vim: set filetype=toml
[default]
jenkins_server_url = "https://jenkins.****.fr"
username = "fl0w"
active = true
api_token = "******************"

**Comment by ismet55555** [comment] 2022-06-21 18:11
There doesn't seem to be anything unusual going on with your credentials file.

That final 400 bad request debug log leads me to believe it's something about the way the request is put together.

Are you able to try both of these and see if that works with :

- Use the `--token` flag to manually pass a token you know is valid
- Remove the `api_token` from the credentials file and let it prompt you for your password:
   - ```toml
     [default]
     .....
     api_token = ""
     ```

If you just put a invalid API token into the request, do you get the exact same error?

**Comment by 3l0w** [comment] 2022-06-21 19:22
I have already tested that same error

**Comment by ismet55555** [comment] 2022-06-23 01:43
So both, `--token` and empty `api_token` credential will give same error?

What about when you place in a invalid token, will it give the same 400 error?
With a invalid token you should get something like:

```
   - Status code:    401 (Unauthorized)
PERMISSION DENIED - Request denied due to insufficient privileges 
```

So something about that request. If you are sure that API token is valid, I would guess it has something to do with the URL. And if you are sure the server base URL is correct, I'm suspecting something with the `/me/api/json` endpoint.

With your web browser, are you able to go to `https://jenkins.****.fr/me/api/json` ?  You should be able to get a JSON object shown in your browser.

**Comment by ismet55555** [comment] 2022-12-06 14:50
Hey it's been a while and I have not heard anything back. I also was not able to reproduce the issue on my end.
Closing this issue.

**Closed by ismet55555** 2022-12-06 14:50 UTC
Labels: bug
